# Generated by Django 3.2.16 on 2024-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Плани'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервіс', 'verbose_name_plural': 'Сервіси'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Підписка', 'verbose_name_plural': 'Підписки'},
        ),
    ]
